### ISSUE TITLE
pretrain stream model

### ISSUE THREAD

**Issue by zichihuanian** [samuel8503/MirrorGAN#1]
hello, thanks for you contribution,  would you like to release the pretrained stream model of CUB and COCO, thanks a lot!

**Comment by samuel8503** [comment]
Both models are uploaded to [Google Drive](https://drive.google.com/drive/folders/1a05Da8_X49VDP0dhoa-yFc49xf5KF_bB?usp=sharing).
You can also check out the training code [here](https://github.com/samuel8503/MirrorGAN/blob/main/code/pretrain_stream.py).
